import array.CheckIfNandItsDoubleExist_1346;
import array.SpecialArray1_3151;
import array.WeightedWordMapping_3838;
import arrays.DIStringMatch_942;
import arrays.IntersectionofTwoArrays2_350;
import arrays.LongestHarmoniousSubsequence_594;
import arrays.MaximumSumWithExactlyKElements_2656;
import arrays.RelativeRanks_506;
import arrays.TeemoAttacking_495;
import hashset.AssignCookies_455;
import matrix.CellswithOddValuesinaMatrix_1252;
import matrix.CheckIfItIsaStraightLine_1232;
import matrix.MinimumTimeVisitingAllPoints_1266;
import matrix.SnakeinMatrix_3248;
import sort.SortIntegersbyTheNumberof1Bits_1356;
import strings.CheckBalancedString_3340;
import strings.CountBinarySubstrings_696;
import strings.DecryptStringfromAlphabettoIntegerMapping_1309;
import strings.FindMaximumNumberofStringPairs_2744;
import strings.FirstMatchingCharacterFromBothEnds_3884;
import strings.LongestPalindrome_409;
import strings.MaximumOddBinaryNumber_2864;
import strings.RepeatedSubstringPattern_459;
import strings.ReplaceAllDigitswithCharacters_1844;

import java.util.Arrays;
import java.util.List;

public class Main {
    public static void main(String[] args) {
        var klass = new LongestPalindrome_409();
        String s = "civilwartestingwhetherthatnaptionoranynartionsoconceivedandsodedicatedcanlongendureWeareqmetonagreatbattlefiemldoftzhatwarWehavecometodedicpateaportionofthatfieldasafinalrestingplaceforthosewhoheregavetheirlivesthatthatnationmightliveItisaltogetherfangandproperthatweshoulddothisButinalargersensewecannotdedicatewecannotconsecratewecannothallowthisgroundThebravelmenlivinganddeadwhostruggledherehaveconsecrateditfaraboveourpoorponwertoaddordetractTgheworldadswfilllittlenotlenorlongrememberwhatwesayherebutitcanneverforgetwhattheydidhereItisforusthelivingrathertobededicatedheretotheulnfinishedworkwhichtheywhofoughtherehavethusfarsonoblyadvancedItisratherforustobeherededicatedtothegreattdafskremainingbeforeusthatfromthesehonoreddeadwetakeincreaseddevotiontothatcauseforwhichtheygavethelastpfullmeasureofdevotionthatweherehighlyresolvethatthesedeadshallnothavediedinvainthatthisnationunsderGodshallhaveanewbirthoffreedomandthatgovernmentofthepeoplebythepeopleforthepeopleshallnotperishfromtheearth";
        System.out.println((klass.longestPalindrome(s)));

    }
}


